### ISSUE TITLE
[LIST] The grand most demanded feature requests tracking list

### ISSUE THREAD

**Issue by kabachuha** [deforum/stable-diffusion#97]
- [ ] Custom folder & file naming option: ex. (flower00001.png, flower00002.png, flower00003.png)

- [ ] Init_Image injection as multiple select frame points. ex. (use robot01.png at frame 17, use flower032.png at frame 106)

- [ ] Footnotes about ranges above values: ex. (contrast, range 0-2, default 1.0)(midas, range -1 to 1, default 0.3)

- [ ] Request for Sharpen/Detail (to combat animation blur) (cv2-sharpen revisit?)

- [ ] Request for upscalers.

- [ ] Request for Face restore.

- [ ] Color matching by interval: ex (instead of match frame 0, match every_x_frames)

- [ ] Custom color channels schedules: ex (saturation_schedule, hue_schedule, Red_schedule, Green_Schedule, Blue_schedule... ect)

- [ ] Interpolation mode display: progress bar needed for completion %frames

- [ ] Interpolation mode to force seed per prompt: ex (0: "prompt"--seed 11 | 10: "next prompt" --seed 1561)

- [ ] Force_Seed_at_frame request: ex (at frame 171, to use seed 271667829)

- [ ] Request for prompt seed syntax ("a golden apple" --seed 18827)

- [ ] "Noodle_Soup" prompt inclusion. (a prompt langauge that allow for keywords and variables like _color_ - which can be randomized)

- [ ] Request textual_inversion

- [ ] Request for VR or Equirectangular Projection (for use in 3D aplications, sky boxes, HDRI images etc)

- [ ] Request for CLIP guidance

- [ ] Request for "Target Image" - diffusion will attempt to head towards the shape/context of a target (opposite of init_image)

- [ ] Request for "Attention Slicing"

- [ ] Video_Input coherance (using previous frame, as in 2D/3D mode with strength_schedule)

- [ ] Video_Input depthmap usage (warp diffusion method) aka RAFT

- [ ] Video Mask to be used in 2D/3D modes also (currently restricted to just Video_Input)

- [ ] Outpainting as border wrap/replicate option. 

- [ ] Request for embedding

- [ ] Request for Memory Efficient Attention

- [ ] Schedule keyframing for the following: Scale, Midas, FOV, Steps, Strength(init), Seed

- [ ] Request for audio2keyframe schedule.

- [ ] Request for add audio file to animation output inside notebook.

- [ ] Request for batch animations (running 10 sets of 1000 max frame outputs each with different seeds or different prompts)

- [ ] Request for local UI/setup/One-Click go.

- [ ] Support for MAC OS

- [ ] Request for non-linear tweening of keyframes - (ie bezier curves between 0:(3), 100:(-2)

- [ ] Request for selecting a specific GPU on multi-GPU systems

- [ ] Request for sliders instead of number entry with an option to include math would make it much more user friendly

**Comment by rethink-studios** [comment]
Request for selecting a specific GPU on multi-GPU systems

**Comment by kabachuha** [comment]
@rethink-studios noted

for now try launching the notebook with CUDA_VISIBLE_DEVICES=1 before the notebook/script

```
CUDA_VISIBLE_DEVICES=1 jupyter notebook
```

**Comment by rethink-studios** [comment]
> 

@kabachuha 
Currently running via python command prompt. Is there a way to activate without using jupyter?

**Comment by kabachuha** [comment]
`CUDA_VISIBLE_DEVICES=1 python Deforum_Stable_Diffusion.py` from the local branch?

**Comment by rethink-studios** [comment]
Yup, Deforum_Stable_Diffusion.py

**Comment by kabachuha** [comment]
Backport https://github.com/deforum-art/deforum-for-automatic1111-webui/commit/ac8fed9ed705b43975dd14f69de3e253e69750dc

https://github.com/deforum-art/deforum-for-automatic1111-webui/commit/9d09ef6be75a0ad379cd2869c4bdc00855e5db33

and

https://github.com/deforum-art/deforum-for-automatic1111-webui/commit/931eeb0be4719b137f836bb7c972ecaab9471c16
